name = "ParameterisedModule"
uuid = "d16e510f-c236-4b74-8eb3-5d2ec9a3ec6e"
authors = ["thautwarm"]
version = "0.1.0"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1"
MLStyle = "^0.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
